services:
  trainer:
    container_name: trainer
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./data:/data"
      - "./models:/models"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       -  driver: nvidia
    #          count: all
    #          capabilities: [gpu]