name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install pandas
          python -m pip install scikit-learn
          python -m pip install pytest

      - name: Run tests
        run: |
          python -m pytest tests/

  train:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install pandas
          python -m pip install scikit-learn
          python -m pip install tensorflow

      - name: Train model
        run: |
          python app.py

      - name: Save model artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfmodel
          path: models/tfmodel.keras

  deploy:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: tfmodel
          path: models/

      - name: Minio Deploy
        uses: lovellfelix/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'test'
          source_dir: 'models'
          target_dir: 'models'