name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install minio
 
      - name: Minio Deploy
        run: |
          python -c "from minio import Minio; client = Minio('${{ secrets.MINIO_ENDPOINT_NO_HTTP }}', access_key='${{ secrets.MINIO_ACCESS_KEY }}', secret_key='${{ secrets.MINIO_SECRET_KEY }}', secure=False); client.fput_object('datastorage', 'keep', 'models/.keep')"
          

  test:
    runs-on: ubuntu-latest
    needs: first
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install pandas
          python -m pip install scikit-learn
          python -m pip install pytest
          python -m pip install dvc
          python -m pip install dvc_s3
          python -m dvc remote modify minio endpointurl ${{ secrets.MINIO_ENDPOINT }}
          python -m dvc remote modify --local minio access_key_id ${{ secrets.MINIO_ACCESS_KEY }}
          python -m dvc remote modify --local minio secret_access_key ${{ secrets.MINIO_SECRET_KEY }}

      - name: DVC Pull
        run: |
          python -m dvc pull -r minio

      - name: Run tests
        run: |
          python -m pytest tests/

  train:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install pandas
          python -m pip install scikit-learn
          python -m pip install tensorflow
          python -m pip install dvc
          python -m pip install dvc_s3
          python -m dvc remote modify minio endpointurl ${{ secrets.MINIO_ENDPOINT }}
          python -m dvc remote modify --local minio access_key_id ${{ secrets.MINIO_ACCESS_KEY }}
          python -m dvc remote modify --local minio secret_access_key ${{ secrets.MINIO_SECRET_KEY }}

      - name: DVC Pull
        run: |
          python -m dvc pull -r minio

      - name: Train model
        run: |
          python src/app.py

      - name: Save model artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfmodel
          path: models/tfmodel.keras

  deploy:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: tfmodel
          path: models/

      - name: Minio Deploy
        run: |
          curl https://dl.min.io/client/mc/release/linux-arm64/mc --create-dirs -o ~/minio-binaries/mc
          chmod +x ~/minio-binaries/mc
          ~/minio-binaries/mc alias set ALIAS ${{ secrets.MINIO_ENDPOINT }} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}

      - name: ls
        run: |
          ls models

      - name: Upload model
        run: |
          mc put models/tfmodel.zip minio/datastorage